// This file will be auto-generated by running: npm run db:types
// For now, providing minimal types to avoid errors

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string
          display_name: string | null
          bio: string | null
          avatar_url: string | null
          trust_score: number
          reputation_available: number
          total_drops: number
          successful_drops: number
          total_validations_given: number
          onboarded: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username: string
          display_name?: string | null
          bio?: string | null
          avatar_url?: string | null
          trust_score?: number
          reputation_available?: number
          total_drops?: number
          successful_drops?: number
          total_validations_given?: number
          onboarded?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string
          display_name?: string | null
          bio?: string | null
          avatar_url?: string | null
          trust_score?: number
          reputation_available?: number
          total_drops?: number
          successful_drops?: number
          total_validations_given?: number
          onboarded?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      drops: {
        Row: {
          id: string
          user_id: string
          track_id: string
          track_name: string
          artist_name: string
          album_name: string | null
          album_art_url: string | null
          spotify_url: string | null
          preview_url: string | null
          context: string
          listening_notes: string | null
          reputation_stake: number
          genres: string[] | null
          mood_tags: string[] | null
          validation_score: number
          validation_count: number
          total_rating_sum: number
          status: string
          expires_at: string
          resolved_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          track_id: string
          track_name: string
          artist_name: string
          album_name?: string | null
          album_art_url?: string | null
          spotify_url?: string | null
          preview_url?: string | null
          context: string
          listening_notes?: string | null
          reputation_stake: number
          genres?: string[] | null
          mood_tags?: string[] | null
          validation_score?: number
          validation_count?: number
          total_rating_sum?: number
          status?: string
          expires_at?: string
          resolved_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          track_id?: string
          track_name?: string
          artist_name?: string
          album_name?: string | null
          album_art_url?: string | null
          spotify_url?: string | null
          preview_url?: string | null
          context?: string
          listening_notes?: string | null
          reputation_stake?: number
          genres?: string[] | null
          mood_tags?: string[] | null
          validation_score?: number
          validation_count?: number
          total_rating_sum?: number
          status?: string
          expires_at?: string
          resolved_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      drop_validations: {
        Row: {
          id: string
          drop_id: string
          validator_id: string
          rating: number
          listened: boolean
          listen_duration_seconds: number | null
          feedback: string | null
          created_at: string
        }
        Insert: {
          id?: string
          drop_id: string
          validator_id: string
          rating: number
          listened?: boolean
          listen_duration_seconds?: number | null
          feedback?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          drop_id?: string
          validator_id?: string
          rating?: number
          listened?: boolean
          listen_duration_seconds?: number | null
          feedback?: string | null
          created_at?: string
        }
      }
      spotify_connections: {
        Row: {
          user_id: string
          access_token: string
          refresh_token: string
          expires_at: string
          spotify_id: string | null
          spotify_email: string | null
          spotify_display_name: string | null
          spotify_country: string | null
          last_synced: string | null
          sync_enabled: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          user_id: string
          access_token: string
          refresh_token: string
          expires_at: string
          spotify_id?: string | null
          spotify_email?: string | null
          spotify_display_name?: string | null
          spotify_country?: string | null
          last_synced?: string | null
          sync_enabled?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          user_id?: string
          access_token?: string
          refresh_token?: string
          expires_at?: string
          spotify_id?: string | null
          spotify_email?: string | null
          spotify_display_name?: string | null
          spotify_country?: string | null
          last_synced?: string | null
          sync_enabled?: boolean
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {}
    Functions: {}
    Enums: {}
  }
}
